PRODUCT_COPY_FILES += \
vendor/htc/evita/proprietary/lib/egl/eglsubAndroid.so \
vendor/htc/evita/proprietary/lib/egl/libEGL_adreno200.so \
vendor/htc/evita/proprietary/lib/egl/libGLESv1_CM_adreno200.so \
vendor/htc/evita/proprietary/lib/egl/libGLESv2_adreno200.so \
vendor/htc/evita/proprietary/lib/egl/libq3dtools_adreno200.so \
vendor/htc/evita/proprietary/lib/hw/camera.msm8960.so \
vendor/htc/evita/proprietary/lib/hw/gps.default.so \
vendor/htc/evita/proprietary/lib/hw/sensors.elite.so \
vendor/htc/evita/proprietary/bin/akmd \
vendor/htc/evita/proprietary/bin/charging \
vendor/htc/evita/proprietary/bin/hci_qcomm_init \
vendor/htc/evita/proprietary/bin/mm-qcamera-daemon \
vendor/htc/evita/proprietary/bin/mpdecision \
vendor/htc/evita/proprietary/bin/netmgrd \
vendor/htc/evita/proprietary/bin/netsharing \
vendor/htc/evita/proprietary/bin/qmuxd \
vendor/htc/evita/proprietary/bin/rmt_storage \
vendor/htc/evita/proprietary/bin/thermald \
vendor/htc/evita/proprietary/bin/time_daemon \
vendor/htc/evita/proprietary/bin/zchgd \
vendor/htc/evita/proprietary/etc/agps_rm \
vendor/htc/evita/proprietary/lib/egl \
vendor/htc/evita/proprietary/lib/hw \
vendor/htc/evita/proprietary/lib/libacdbloader.so \
vendor/htc/evita/proprietary/lib/libaudcal.so \
vendor/htc/evita/proprietary/lib/libC2D2.so \
vendor/htc/evita/proprietary/lib/libcamera_client.so \
vendor/htc/evita/proprietary/lib/libcameraface.so \
vendor/htc/evita/proprietary/lib/libcamerapp.so \
vendor/htc/evita/proprietary/lib/libcameraservice.so \
vendor/htc/evita/proprietary/lib/libchromatix_s5k3h2yx_default_video.so \
vendor/htc/evita/proprietary/lib/libchromatix_s5k3h2yx_hdr.so \
vendor/htc/evita/proprietary/lib/libchromatix_s5k3h2yx_hfr.so \
vendor/htc/evita/proprietary/lib/libchromatix_s5k3h2yx_preview.so \
vendor/htc/evita/proprietary/lib/libchromatix_s5k3h2yx_zsl.so \
vendor/htc/evita/proprietary/lib/libdiag.so \
vendor/htc/evita/proprietary/lib/libdsi_netctrl.so \
vendor/htc/evita/proprietary/lib/libdsutils.so \
vendor/htc/evita/proprietary/lib/libDxOAF.so \
vendor/htc/evita/proprietary/lib/libgemini.so \
vendor/htc/evita/proprietary/lib/libgps.so \
vendor/htc/evita/proprietary/lib/libgps.utils.so \
vendor/htc/evita/proprietary/lib/libgsl.so \
vendor/htc/evita/proprietary/lib/libidl.so \
vendor/htc/evita/proprietary/lib/libloc_adapter.so \
vendor/htc/evita/proprietary/lib/libloc_api_v02.so \
vendor/htc/evita/proprietary/lib/libloc_eng.so \
vendor/htc/evita/proprietary/lib/libloc_ext.so \
vendor/htc/evita/proprietary/lib/libmmcamera_frameproc.so \
vendor/htc/evita/proprietary/lib/libmmcamera_rawchipproc.so \
vendor/htc/evita/proprietary/lib/libmmcamera_statsproc30.so \
vendor/htc/evita/proprietary/lib/libmm-color-convertor.so \
vendor/htc/evita/proprietary/lib/libmmipl.so \
vendor/htc/evita/proprietary/lib/libmmjpeg.so \
vendor/htc/evita/proprietary/lib/libmmosal.so \
vendor/htc/evita/proprietary/lib/libmmparser_divxdrmlib.so \
vendor/htc/evita/proprietary/lib/libmmparser.so \
vendor/htc/evita/proprietary/lib/libnetmgr.so \
vendor/htc/evita/proprietary/lib/liboemcamera.so \
vendor/htc/evita/proprietary/lib/libOlaEngine.so \
vendor/htc/evita/proprietary/lib/libOpenVG.so \
vendor/htc/evita/proprietary/lib/libposteffect.so \
vendor/htc/evita/proprietary/lib/libqc-opt.so \
vendor/htc/evita/proprietary/lib/libqdi.so \
vendor/htc/evita/proprietary/lib/libqdp.so \
vendor/htc/evita/proprietary/lib/libqmi_cci.so \
vendor/htc/evita/proprietary/lib/libqmi_common_so.so \
vendor/htc/evita/proprietary/lib/libqmi_csi.so \
vendor/htc/evita/proprietary/lib/libqmi_encdec.so \
vendor/htc/evita/proprietary/lib/libqmiservices.so \
vendor/htc/evita/proprietary/lib/libqmi.so \
vendor/htc/evita/proprietary/lib/libril-qc-qmi-1.so \
vendor/htc/evita/proprietary/lib/libril-qcril-hook-oem.so \
vendor/htc/evita/proprietary/lib/libril.so \
vendor/htc/evita/proprietary/lib/libsc-a2xx.so \
vendor/htc/evita/proprietary/lib/libv8.so
